### ISSUE TITLE
Versions 0.1.x are incorrectly listed as compatible with Ruby 2.3

### ISSUE THREAD

**Issue by miloprice** [ruby/base64#22]
All versions of base64 use `String#unpack1`, introduced in Ruby 2.4.

In https://github.com/ruby/base64/pull/17, the gemspec was updated to declare Ruby `>= 2.4` as a dependency, but this change was only published in base64 v0.2.0. As a result, [v0.1.0](https://rubygems.org/gems/base64/versions/0.1.0) and [v0.1.1](https://rubygems.org/gems/base64/versions/0.1.1) are still published as being compatible with Ruby 2.3, despite causing base64 decoding to fail when run in a Ruby 2.3 app.

To remedy this, would it be possible to do either of the following:

1. Yank v0.1.0 and v0.1.1, since they have incorrect dependencies declared, and publish new versions v0.1.0.1 and v0.1.1.1 with correctly declared Ruby >= 2.4
2. Publish a Ruby 2.3-compatible version v0.1.2 that doesn't rely on `String#unpack1`

If the second option would be preferable, I can put up a PR.

**Comment by hsbt** [comment]
Done https://github.com/ruby/base64/releases/tag/v0.1.2
